language: android

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
 - TRAVIS_NODE_VERSION=10 TRAVIS_RUBY_VERSION=2.6.0 RUST_TOOLCHAIN=nightly RELEASE=false

cache:
 - bundler
 - cargo

before_install:
 - yes | sdkmanager "platforms;android-27"
 - yes | sdkmanager "ndk-bundle"
 - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION;
 - rvm install $TRAVIS_RUBY_VERSION && rvm use $TRAVIS_RUBY_VERSION && gem update --system && gem install bundle && bundle install
 - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $RUST_TOOLCHAIN && source $HOME/.cargo/env
 - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
 - ./scripts/setup-rust-with-ndk.sh

install:
 - make aw-server-rust
 - make aw-webui

script:
 - ./gradlew clean lint test
 - ./gradlew connectedAndroidTest || true

before_deploy:
 - openssl aes-256-cbc -K $encrypted_aac99b59139e_key -iv $encrypted_aac99b59139e_iv -in android.jks.enc -out android.jks -d
 - openssl aes-256-cbc -K $encrypted_c39c3bebf85c_key -iv $encrypted_c39c3bebf85c_iv -in fastlane/api-8546008605074111507-287154-450dc77b365f.json.enc -out fastlane/api-8546008605074111507-287154-450dc77b365f.json -d

deploy:
 # Production version
 - provider: script
   script: bash scripts/deploy.sh
   skip_cleanup: true
   on:
     tags: true
 # Open beta (nightlys)
#- provider: script
#  script: bash scripts/deploy.sh
#  skip_cleanup: true
#  on:
#    branch: master

