language: android

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - yes | sdkmanager "platforms;android-27"

script:
 - ./gradlew clean lint test


