language: android

android:
  components:
    - build-tools-28.0.3
    - android-28
    - extra
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
 - openssl aes-256-cbc -K $encrypted_aac99b59139e_key -iv $encrypted_aac99b59139e_iv \
   -in android.jks.enc -out android.jks \
   -d
 - yes | sdkmanager "platforms;android-27"

script:
 - ./gradlew clean lint test
 - ./gradlew connectedAndroidTest || true

before_deploy:
 - ./gradlew assembleRelease
 - mv mobile/build/outputs/apk/release/mobile-release-unsigned.apk aw-android.apk
 - jarsigner -verbose -sigalg SHA1withRSA -storepass $storepass -keypass $keypass -digestalg SHA1 -keystore android.jks aw-android.apk activitywatch
 - zipalign -v 4 aw-android.apk aw-android-release.apk
 - supply init -j PATH_TO_/FOO.json -p MY.PACKAGE.NAME


